title: GlitchGecko
tagline: A Cybersecurity student's blog
description: Welcome to my website!
show_downloads: false
site_favicon: favicon.ico

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://glitchgecko.xyz" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: GlitchGecko
image: https://avatars.githubusercontent.com/u/17220280?s=400&u=7a220ef0586188f17e0605797c29d04b46635186&v=4
username: GlitchGecko
user_title: GlitchGecko
email: nvformella@gmail.com
github_username: GlitchGecko

  
plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'projects', 'contact', 'posts', 'tags']
